### ISSUE TITLE
BI-LSTM for aspects 这个是干嘛用的

### ISSUE THREAD

**Issue by xuanzebi** [idorce/sentiment-analysis-ccf-bdci#1]
BI-LSTM for aspects 这个是干嘛用的....

**Comment by idorce** [comment]
For aspect encoding...

**Comment by idorce** [comment]
通过这个得到aspect的encoding，之后通过点积操作将句子每个词的encoding投影到这个aspect encoding上来。

**Comment by xuanzebi** [comment]
嗯.....好的 我再去研读一下论文去。。顺便在问个问题哈。。。
`
 def f1(y_true, y_pred):
    y_true, y_pred = to_class_label(y_true), to_class_label(y_pred)
    zeros = K.zeros_like(y_true)
    true_not_zero = K.cast(K.not_equal(y_true, zeros), K.floatx())
    true_zero = K.cast(K.equal(y_true, zeros), K.floatx())
    pred_not_zero = K.cast(K.not_equal(y_pred, zeros), K.floatx())
    pred_zero = K.cast(K.equal(y_pred, zeros), K.floatx())
    pred_not_true = K.cast(K.not_equal(y_true, y_pred), K.floatx())
    pred_true = K.cast(K.equal(y_true, y_pred), K.floatx())
    tp = K.sum(true_not_zero * pred_not_zero * pred_true + K.epsilon())
    fp = K.sum(true_not_zero * pred_not_zero * pred_not_true + true_zero * pred_not_zero + K.epsilon())
    fn = K.sum(true_not_zero * pred_zero + K.epsilon())
    p = tp / (tp + fp + K.epsilon()) # 准确率
    r = tp / (tp + fn + K.epsilon())
    f1 = 2 * p * r / (p + r + K.epsilon())
    return f1

`

这个f1值怎么计算的我不是太理解....能详细讲一下吗
