### ISSUE TITLE
这个f1值怎么计算的

### ISSUE THREAD

**Issue by idorce** [idorce/sentiment-analysis-ccf-bdci#2]
```python
def f1(y_true, y_pred):
    """Task-required F1 score."""
    y_true, y_pred = to_class_label(y_true), to_class_label(y_pred)    
    zeros = K.zeros_like(y_true)
    
    true_not_zero = K.cast(K.not_equal(y_true, zeros), K.floatx())
    true_zero = K.cast(K.equal(y_true, zeros), K.floatx())
    pred_not_zero = K.cast(K.not_equal(y_pred, zeros), K.floatx())
    pred_zero = K.cast(K.equal(y_pred, zeros), K.floatx())
    pred_not_true = K.cast(K.not_equal(y_true, y_pred), K.floatx())
    pred_true = K.cast(K.equal(y_true, y_pred), K.floatx())
    
    tp = K.sum(true_not_zero * pred_not_zero * pred_true + K.epsilon())
    fp = K.sum(true_not_zero * pred_not_zero * pred_not_true +
               true_zero * pred_not_zero + K.epsilon())
    fn = K.sum(true_not_zero * pred_zero + K.epsilon())
    
    p = tp / (tp + fp + K.epsilon())
    r = tp / (tp + fn + K.epsilon())
    f1 = 2 * p * r / (p + r + K.epsilon())
    return f1
```

这个f1值怎么计算的我不是太理解....能详细讲一下吗

_Originally posted by @xuanzebi in https://github.com/idorce/sentiment-analysis-ccf-bdci/issues/1#issuecomment-441341422_

**Comment by idorce** [comment]
这个比赛的F1值（check [here](https://github.com/idorce/sentiment-analysis-ccf-bdci/blob/master/f1Evaluate.png)）因为涉及到不同aspect的情感而有些不同。

这在该模型的输出设定下，y≠0指这个句子有谈论这个aspect，并且情感为（0，1，-1）三个之一。
```python
senti_label_id  = {'无关': 0, 0: 1, 1: 2, -1: 3}
```
因此，F1计算中的TP、FP（两种情况数之和）、FN有如下等价关系。

| |y_true||y_pred||y_true vs. y_pred|
|-|:-:|-|:-:|-|:-:|
|TP|≠0|and|≠0|and|=|
|FP|≠0|and|≠0|and|≠|
|FP|=0|and|≠0|and|= or ≠|
|FN|≠0|and|=0|and|= or ≠|

f1函数中 true_not_zero 即指 y_true≠0，true_zero 即指 y_true=0，依此类推。

**Comment by xuanzebi** [comment]
为什么用了你的模型 ，最后得分只有0.62😭

**Comment by idorce** [comment]
_(:_」∠)_ 这个是在复赛数据上跑的，对初赛数据可能要换下词向量、调下模型什么的。

**Comment by xuanzebi** [comment]
emmm..ok好的 感谢

**Comment by xuanzebi** [comment]
顺带想问下。。。如果是初赛数据的话，大概模型的哪些部分、哪些参数需要调整下。。
我是小白😭

**Comment by idorce** [comment]
这个视问题具体情况根据经验了吧。这也是我第一次参加这样的比赛呢，一起加油吧。

**Comment by xuanzebi** [comment]
好滴 thanks 加油
