### ISSUE TITLE
the file name is wrong

### ISSUE THREAD

**Issue by Supergirl12138** [idorce/sentiment-analysis-ccf-bdci#4]
you write embeding in file named embeddings_.p, but you read embeddings.p.Are they the same file?

**Comment by idorce** [comment]
Yes, they point to the same file. It's been a while since I wrote these. I guess I just use `embeddings.p` at first, which contains all the word embeddings. After pruning some embeddings, I named it `embeddings_.p`.

**Comment by Supergirl12138** [comment]
thanks，but how did you pruning embeddings？

**Comment by idorce** [comment]
It's in the section 2 of `getEmbedding.ipynb`.

**Comment by Supergirl12138** [comment]
I see , 3Q
